services:
  opensearch:
    #image: opensearchproject/opensearch:2.11.1 # safe with fylr before v6.9.0
    image: opensearchproject/opensearch:2.12.0 # needs at least fylr v6.9.0
    container_name: opensearch
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - network.publish_host=127.0.0.1
      - plugins.security.disabled=true
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=EXAMPLEq_-945873205"
    volumes:
      - "/srv/fylr/indexer:/usr/share/opensearch/data"
    command: >
      /bin/sh -c "./bin/opensearch-plugin install analysis-icu; /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    networks:
      - fylr
    logging:
      driver: "journald"

  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_DB: 'fylr'
      POSTGRES_USER: 'fylr'
      POSTGRES_PASSWORD: 'fylr'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/srv/fylr/postgres:/var/lib/postgresql/data"
      - "/srv/fylr/sqlbackups:/mnt"
    command: >
      -c work_mem=64MB
      -c maintenance_work_mem=32MB
      -c max_wal_size=512MB
      -c max_connections=100
    networks:
      - fylr
    logging:
      driver: "journald"

  fylr:
    image: docker.fylr.io/fylr/fylr:latest
    hostname: fylr.localhost
    container_name: fylr
    #restart: always # always: recommended after letsencrypt is tested
    ports:
      - "443:443" # main https access to webfrontend
      - "80:80" # one channel to get a certificate from letsencrypt
    depends_on:
      - opensearch
      - postgresql
    networks:
      - fylr
    volumes:
      - "/srv/fylr/config/fylr:/fylr/config"
      - "/srv/fylr/assets:/srv"
      - "/srv/fylr/backups:/fylr/files/backups"     # /inspect/system/backups/
      - "/srv/fylr/migration:/fylr/files/migration" # /inspect/backup/
    logging:
      driver: "journald"

networks:
  fylr:
