services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - network.publish_host=127.0.0.1
      - plugins.security.disabled=true
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=EXAMPLEq_-945873205"
    volumes:
      - "/srv/fylr/indexer:/usr/share/opensearch/data"
    command: >
      /bin/sh -c "./bin/opensearch-plugin install analysis-icu; /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    networks:
      - fylr
    logging:
      driver: "journald"

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: 'fylr'
      POSTGRES_PASSWORD: 'EXAMPLE'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/srv/fylr/postgres:/var/lib/postgresql/data"
      - "/srv/fylr/sqlbackups:/mnt"
    command: >
      -c work_mem=64MB
      -c maintenance_work_mem=32MB
      -c max_wal_size=512MB
      -c max_connections=100
    networks:
      - fylr
    logging:
      driver: "journald"

  fylr-EXAMPLE1:
    image: docker.fylr.io/fylr/fylr:latest
    hostname: fylr-EXAMPLE1.localhost
    container_name: fylr-EXAMPLE1
    restart: always
    ports:
      - "127.0.0.1:81:80"
    depends_on:
      - opensearch
      - postgresql
    networks:
      - fylr
    volumes:
      - "/srv/fylr/fylr-EXAMPLE1/config/fylr:/fylr/config"
      - "/srv/fylr/fylr-EXAMPLE1/assets:/srv"
      - "/srv/fylr/fylr-EXAMPLE1/backups:/fylr/files/backups"     # /inspect/system/backups/ and /backupmanager
      - "/srv/fylr/fylr-EXAMPLE1/migration:/fylr/files/migration" # /inspect/migration/
    logging:
      driver: "journald"

  fylr-EXAMPLE2:
    image: docker.fylr.io/fylr/fylr:latest
    hostname: fylr-EXAMPLE2.localhost
    container_name: fylr-EXAMPLE2
    restart: always
    ports:
      - "127.0.0.1:82:80"
    depends_on:
      - opensearch
      - postgresql
    networks:
      - fylr
    volumes:
      - "/srv/fylr/fylr-EXAMPLE2/config/fylr:/fylr/config"
      - "/srv/fylr/fylr-EXAMPLE2/assets:/srv"
      - "/srv/fylr/fylr-EXAMPLE2/backups:/fylr/files/backups"     # /inspect/system/backups/ and /backupmanager
      - "/srv/fylr/fylr-EXAMPLE2/migration:/fylr/files/migration" # /inspect/migration/
    logging:
      driver: "journald"

networks:
  fylr:
